version: '3.9'

services:
  db:
    image: postgres:15
    container_name: logyca_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: logyca_db
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: logyca_api
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/logyca_db
    depends_on:
      - db

  worker:
    build: .
    container_name: logyca_worker
    command: python -m app.workers.sales_worker
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/logyca_db
    depends_on:
      - db
      - api

  n8n:
    image: n8nio/n8n:latest
    container_name: logyca_n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=logyca_db
      - DB_POSTGRESDB_USER=user
      - DB_POSTGRESDB_PASSWORD=pass
    depends_on:
      - db

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: logyca_azure_emulator
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
